/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controlador.ControladorArea;
import Controlador.ControladorEmpleado;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leydi
 */
public class EmpleadosPorArea extends javax.swing.JPanel {
    
    ControladorEmpleado controlempleado = new ControladorEmpleado();
    ControladorArea controlarea = new ControladorArea();
    /**
     * Creates new form EmpleadosPorArea
     */
    public EmpleadosPorArea() {
        initComponents();
        
        DefaultTableModel model;
        DefaultComboBoxModel Areas;
        model = new DefaultTableModel(){
             public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
        };
        Areas = new DefaultComboBoxModel();
        TablaEmpleadoArea.setModel(model);
        model.addColumn("Nombre");
        model.addColumn("Cargo");
        TablaEmpleadoArea.getTableHeader().setReorderingAllowed(false);
        controlempleado.Select_empleado(model);
        controlarea.Select_nombrearea(Areas);
        this.Areas.setModel(Areas);
        jScrollPane1.setViewportView(TablaEmpleadoArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleadoArea = new javax.swing.JTable();
        Areas = new javax.swing.JComboBox<>();
        Actualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Restablecer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        TablaEmpleadoArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Identificacion", "Nombre", "Cargo"
            }
        ));
        TablaEmpleadoArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEmpleadoAreaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaEmpleadoArea);

        Areas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Areas" }));

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione el Area que desea:");

        Restablecer.setText("Restablecer");
        Restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestablecerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Listar Empleados");

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Areas, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Restablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Actualizar)
                    .addComponent(Restablecer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TablaEmpleadoAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEmpleadoAreaMouseClicked
        int row = TablaEmpleadoArea.rowAtPoint(evt.getPoint());
        DefaultTableModel tablaequipment = (DefaultTableModel) TablaEmpleadoArea.getModel();
        String dato=String.valueOf(tablaequipment.getValueAt(TablaEmpleadoArea.getSelectedRow(), 0));

    }//GEN-LAST:event_TablaEmpleadoAreaMouseClicked

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        
        DefaultTableModel model;
        model = new DefaultTableModel();
        model = new DefaultTableModel(){
             public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
        };
        TablaEmpleadoArea.setModel(model);
        model.addColumn("Nombre");
        model.addColumn("Cargo");
        TablaEmpleadoArea.getTableHeader().setReorderingAllowed(false);
        controlempleado. Select_empleadoarea(model,Areas.getSelectedItem().toString());
        jScrollPane1.setViewportView(TablaEmpleadoArea);
    }//GEN-LAST:event_ActualizarActionPerformed

    private void RestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestablecerActionPerformed
        DefaultTableModel model;
        model = new DefaultTableModel(){
             public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
        };
        TablaEmpleadoArea.setModel(model);
        model.addColumn("Nombre");
        model.addColumn("Cargo");
        TablaEmpleadoArea.getTableHeader().setReorderingAllowed(false);
        controlempleado.Select_empleado(model);
        jScrollPane1.setViewportView(TablaEmpleadoArea);
    }//GEN-LAST:event_RestablecerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JComboBox<String> Areas;
    private javax.swing.JButton Restablecer;
    private javax.swing.JTable TablaEmpleadoArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
