/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Leidy
 */
public class FormFormula extends javax.swing.JPanel {

    /**
     * Creates new form FormArea
     */
    public FormFormula() {
        initComponents();
        
        ImageIcon imagen1=new ImageIcon(getClass().getResource("/Images/prescription.png"));
        Icon img1 = new ImageIcon(imagen1.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        RegistrarFormula.setIcon(img1);
        
        ImageIcon imagen2=new ImageIcon(getClass().getResource("/Images/prescription.png"));
        Icon img2 = new ImageIcon(imagen2.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        EditarFormula.setIcon(img2);
        
        ImageIcon imagen5=new ImageIcon(getClass().getResource("/Images/prescription.png"));
        Icon img5 = new ImageIcon(imagen5.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        ListarFormula.setIcon(img5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrarFormula = new javax.swing.JButton();
        EditarFormula = new javax.swing.JButton();
        ListarFormula = new javax.swing.JButton();

        RegistrarFormula.setText("Registrar Formula");
        RegistrarFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarFormulaActionPerformed(evt);
            }
        });

        EditarFormula.setText("Editar Formula");
        EditarFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarFormulaActionPerformed(evt);
            }
        });

        ListarFormula.setText("Listar Formula");
        ListarFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarFormulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(RegistrarFormula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(EditarFormula)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(ListarFormula)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarFormula)
                    .addComponent(EditarFormula))
                .addGap(42, 42, 42)
                .addComponent(ListarFormula)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarFormulaActionPerformed
        // TODO add your handling code here:
       RegistroFormula registroformula = new RegistroFormula();
       registroformula.setSize(600, 450);
       registroformula.setLocation(0, 0);
       this.removeAll();
       this.add(registroformula, null);
       this.revalidate();
       this.repaint();
    }//GEN-LAST:event_RegistrarFormulaActionPerformed

    private void EditarFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarFormulaActionPerformed
        // TODO add your handling code here:
       EditarFormula editarformula = new EditarFormula();
       editarformula.setSize(600, 450);
       editarformula.setLocation(0, 0);
       this.removeAll();
       this.add(editarformula, null);
       this.revalidate();
       this.repaint();
    }//GEN-LAST:event_EditarFormulaActionPerformed

    private void ListarFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarFormulaActionPerformed
        // TODO add your handling code here:
       ListarFormula listarformula = new ListarFormula();
       listarformula.setSize(600, 450);
       listarformula.setLocation(0, 0);
       this.removeAll();
       this.add(listarformula, null);
       this.revalidate();
       this.repaint();
    }//GEN-LAST:event_ListarFormulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarFormula;
    private javax.swing.JButton ListarFormula;
    private javax.swing.JButton RegistrarFormula;
    // End of variables declaration//GEN-END:variables
}
