/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Leidy
 */
public class FormEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form FormEmpleados
     */
    public FormEmpleados() {
        initComponents();
        
        ImageIcon imagen1=new ImageIcon(getClass().getResource("/Images/doctor.png"));
        Icon img1 = new ImageIcon(imagen1.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        RegistrarMedico.setIcon(img1);
        
        ImageIcon imagen2=new ImageIcon(getClass().getResource("/Images/doctor.png"));
        Icon img2 = new ImageIcon(imagen2.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        EditarMedico.setIcon(img2);
        
        ImageIcon imagen3=new ImageIcon(getClass().getResource("/Images/nurse.png"));
        Icon img3 = new ImageIcon(imagen3.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        EditarEnfermera.setIcon(img3);
        
        ImageIcon imagen4=new ImageIcon(getClass().getResource("/Images/nurse.png"));
        Icon img4 = new ImageIcon(imagen4.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        RegistrarEnfermera.setIcon(img4);
        
        ImageIcon imagen5=new ImageIcon(getClass().getResource("/Images/shirt.png"));
        Icon img5 = new ImageIcon(imagen5.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        Listar.setIcon(img5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrarMedico = new javax.swing.JButton();
        EditarMedico = new javax.swing.JButton();
        EditarEnfermera = new javax.swing.JButton();
        RegistrarEnfermera = new javax.swing.JButton();
        Listar = new javax.swing.JButton();

        RegistrarMedico.setText("Registrar Médico");
        RegistrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarMedicoActionPerformed(evt);
            }
        });

        EditarMedico.setText("Editar Médico");
        EditarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarMedicoActionPerformed(evt);
            }
        });

        EditarEnfermera.setText("Editar Enfermera");
        EditarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarEnfermeraActionPerformed(evt);
            }
        });

        RegistrarEnfermera.setText("Registrar Enfermera");
        RegistrarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEnfermeraActionPerformed(evt);
            }
        });

        Listar.setText("Listar empleados por area");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegistrarEnfermera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegistrarMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EditarEnfermera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditarMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(Listar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarMedico)
                    .addComponent(EditarMedico))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditarEnfermera)
                    .addComponent(RegistrarEnfermera))
                .addGap(54, 54, 54)
                .addComponent(Listar)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarMedicoActionPerformed
        RegistrarMedico registrarmedico = new RegistrarMedico();
        registrarmedico.setSize(600, 450);
        registrarmedico.setLocation(0,0);
        this.removeAll();
        this.add(registrarmedico, null);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_RegistrarMedicoActionPerformed

    private void EditarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarMedicoActionPerformed
        EditarMedico editarmedico = new EditarMedico();
        editarmedico.setSize(600, 450);
        editarmedico.setLocation(0,0);
        this.removeAll();
        this.add(editarmedico, null);
        this.revalidate();
        this.repaint();
        
    }//GEN-LAST:event_EditarMedicoActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        EmpleadosPorArea empleadosporarea = new EmpleadosPorArea();
        empleadosporarea.setSize(600, 450);
        empleadosporarea.setLocation(0,0);
        this.removeAll();
        this.add(empleadosporarea, null);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_ListarActionPerformed

    private void RegistrarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEnfermeraActionPerformed
        RegistroEnfermera registroenfermera = new RegistroEnfermera();
        registroenfermera.setSize(600, 450);
        registroenfermera.setLocation(0,0);
        this.removeAll();
        this.add(registroenfermera, null);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_RegistrarEnfermeraActionPerformed

    private void EditarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarEnfermeraActionPerformed
        EditarEnfermera editarenfermera = new EditarEnfermera();
        editarenfermera.setSize(600, 450);
        editarenfermera.setLocation(0,0);
        this.removeAll();
        this.add(editarenfermera, null);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_EditarEnfermeraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarEnfermera;
    private javax.swing.JButton EditarMedico;
    private javax.swing.JButton Listar;
    private javax.swing.JButton RegistrarEnfermera;
    private javax.swing.JButton RegistrarMedico;
    // End of variables declaration//GEN-END:variables
}
