/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Leidy
 */
public class FormCampana extends javax.swing.JPanel {

    /**
     * Creates new form FormCampaña
     */
    public FormCampana() {
        initComponents();
         ImageIcon imagen1=new ImageIcon(getClass().getResource("/Images/tag.png"));
        Icon img1 = new ImageIcon(imagen1.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        RegistroCampana.setIcon(img1);
        
        ImageIcon imagen2=new ImageIcon(getClass().getResource("/Images/tag.png"));
        Icon img2 = new ImageIcon(imagen2.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        EditarCampana.setIcon(img2);
        
        ImageIcon imagen5=new ImageIcon(getClass().getResource("/Images/tag.png"));
        Icon img5 = new ImageIcon(imagen5.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        ListarCampana.setIcon(img5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistroCampana = new javax.swing.JButton();
        EditarCampana = new javax.swing.JButton();
        ListarCampana = new javax.swing.JButton();

        RegistroCampana.setText("Registrar Campaña");
        RegistroCampana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroCampanaActionPerformed(evt);
            }
        });

        EditarCampana.setText("Editar Campaña");
        EditarCampana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarCampanaActionPerformed(evt);
            }
        });

        ListarCampana.setText("Listar Campaña");
        ListarCampana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarCampanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(RegistroCampana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(EditarCampana)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(ListarCampana)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistroCampana)
                    .addComponent(EditarCampana))
                .addGap(42, 42, 42)
                .addComponent(ListarCampana)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroCampanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroCampanaActionPerformed
       RegistroCampana registrocampana = new RegistroCampana();
       registrocampana.setSize(600,450);
       registrocampana.setLocation(0, 0);
       this.removeAll();
       this.add(registrocampana,null);
       this.revalidate();
       this.repaint();
    }//GEN-LAST:event_RegistroCampanaActionPerformed

    private void EditarCampanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarCampanaActionPerformed
       EditarCampana editarcampana = new EditarCampana();
       editarcampana.setSize(600,450);
       editarcampana.setLocation(0, 0);
       this.removeAll();
       this.add(editarcampana,null);
       this.revalidate();
       this.repaint();
    }//GEN-LAST:event_EditarCampanaActionPerformed

    private void ListarCampanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarCampanaActionPerformed
       ListarCampanas listarcampana = new ListarCampanas();
       listarcampana.setSize(600,450);
       listarcampana.setLocation(0, 0);
       this.removeAll();
       this.add(listarcampana,null);
       this.revalidate();
       this.repaint();
    }//GEN-LAST:event_ListarCampanaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarCampana;
    private javax.swing.JButton ListarCampana;
    private javax.swing.JButton RegistroCampana;
    // End of variables declaration//GEN-END:variables
}
