/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Leidy
 */
public class FormArea extends javax.swing.JPanel {

    /**
     * Creates new form FormArea
     */
    public FormArea() {
        initComponents();
        
        ImageIcon imagen1=new ImageIcon(getClass().getResource("/Images/placeholder.png"));
        Icon img1 = new ImageIcon(imagen1.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        RegistrarArea.setIcon(img1);
        
        ImageIcon imagen2=new ImageIcon(getClass().getResource("/Images/placeholder.png"));
        Icon img2 = new ImageIcon(imagen2.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        EditarArea.setIcon(img2);
        
        ImageIcon imagen5=new ImageIcon(getClass().getResource("/Images/placeholder.png"));
        Icon img5 = new ImageIcon(imagen5.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        ListarArea.setIcon(img5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrarArea = new javax.swing.JButton();
        EditarArea = new javax.swing.JButton();
        ListarArea = new javax.swing.JButton();

        RegistrarArea.setText("Registrar Area");
        RegistrarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarAreaActionPerformed(evt);
            }
        });

        EditarArea.setText("Editar Area");
        EditarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarAreaActionPerformed(evt);
            }
        });

        ListarArea.setText("Listar Areas");
        ListarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegistrarArea, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(EditarArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListarArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(RegistrarArea)
                .addGap(39, 39, 39)
                .addComponent(EditarArea)
                .addGap(34, 34, 34)
                .addComponent(ListarArea)
                .addGap(96, 96, 96))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarAreaActionPerformed
       RegistroArea registroarea = new RegistroArea();
       registroarea.setSize(600, 450);
       registroarea.setLocation(0, 0);
       this.removeAll();
       this.add(registroarea, null);
       this.revalidate();
       this.repaint();
    }//GEN-LAST:event_RegistrarAreaActionPerformed

    private void EditarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarAreaActionPerformed
       EditarArea editararea = new EditarArea();
       editararea.setSize(600, 450);
       editararea.setLocation(0, 0);
       this.removeAll();
       this.add(editararea, null);
       this.revalidate();
       this.repaint();
    }//GEN-LAST:event_EditarAreaActionPerformed

    private void ListarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarAreaActionPerformed
       ListarAreas listarararea = new ListarAreas();
       listarararea.setSize(600, 450);
       listarararea.setLocation(0, 0);
       this.removeAll();
       this.add(listarararea, null);
       this.revalidate();
       this.repaint();
    }//GEN-LAST:event_ListarAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarArea;
    private javax.swing.JButton ListarArea;
    private javax.swing.JButton RegistrarArea;
    // End of variables declaration//GEN-END:variables
}
