/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Juan David
 */
public class InterfazAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazAdministrador() {
        initComponents();
        this.setResizable(false);
        ImageIcon imagen1=new ImageIcon(getClass().getResource("/Images/hospital.png"));
        Icon img1 = new ImageIcon(imagen1.getImage().getScaledInstance(LabelImagen.getWidth(),LabelImagen.getHeight(), Image.SCALE_DEFAULT));
        LabelImagen.setIcon(img1);
        
        ImageIcon imagen2=new ImageIcon(getClass().getResource("/Images/medicine-2.png"));
        Icon img2 = new ImageIcon(imagen2.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        Perfil.setIcon(img2);
        
        ImageIcon imagen3=new ImageIcon(getClass().getResource("/Images/id-card.png"));
        Icon img3 = new ImageIcon(imagen3.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        Empleados.setIcon(img3);
        
        ImageIcon imagen4=new ImageIcon(getClass().getResource("/Images/mask.png"));
        Icon img4 = new ImageIcon(imagen4.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        Paciente.setIcon(img4);
        
        ImageIcon imagen5=new ImageIcon(getClass().getResource("/Images/placeholder.png"));
        Icon img5 = new ImageIcon(imagen5.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        Area.setIcon(img5);
        
        ImageIcon imagen6=new ImageIcon(getClass().getResource("/Images/hospital-bed.png"));
        Icon img6 = new ImageIcon(imagen6.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        Camas.setIcon(img6);
        
        ImageIcon imagen7=new ImageIcon(getClass().getResource("/Images/tag.png"));
        Icon img7 = new ImageIcon(imagen7.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        Campaña.setIcon(img7);
        
        ImageIcon imagen8=new ImageIcon(getClass().getResource("/Images/hospital-2.png"));
        Icon img8 = new ImageIcon(imagen8.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        Citas.setIcon(img8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        PanelActividades = new javax.swing.JPanel();
        Perfil = new javax.swing.JButton();
        Empleados = new javax.swing.JButton();
        Paciente = new javax.swing.JButton();
        Area = new javax.swing.JButton();
        Camas = new javax.swing.JButton();
        Campaña = new javax.swing.JButton();
        Citas = new javax.swing.JButton();
        LabelImagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Informes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        PanelActividades.setBackground(new java.awt.Color(231, 235, 249));

        javax.swing.GroupLayout PanelActividadesLayout = new javax.swing.GroupLayout(PanelActividades);
        PanelActividades.setLayout(PanelActividadesLayout);
        PanelActividadesLayout.setHorizontalGroup(
            PanelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        PanelActividadesLayout.setVerticalGroup(
            PanelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Perfil.setText("Mi perfil");
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });

        Empleados.setText("Empleados");
        Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadosActionPerformed(evt);
            }
        });

        Paciente.setText("Pacientes");
        Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacienteActionPerformed(evt);
            }
        });

        Area.setText("Areas");
        Area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaActionPerformed(evt);
            }
        });

        Camas.setText("Camas");
        Camas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamasActionPerformed(evt);
            }
        });

        Campaña.setText("Campañas");
        Campaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampañaActionPerformed(evt);
            }
        });

        Citas.setText("Citas");
        Citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitasActionPerformed(evt);
            }
        });

        LabelImagen.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        LabelImagen.setForeground(new java.awt.Color(255, 255, 255));
        LabelImagen.setText("ImagenHospital");
        LabelImagen.setToolTipText("");
        LabelImagen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ClinicalSystem");

        Informes.setText("Informes");
        Informes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Campaña, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(Citas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Camas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Paciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(Informes))
                    .addComponent(PanelActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Perfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Empleados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Paciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Area)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Camas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campaña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Citas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Informes))
                        .addGap(18, 18, 18)
                        .addComponent(PanelActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jMenu1.setText("Opciones");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadosActionPerformed
        FormEmpleados formempleados = new FormEmpleados();
        formempleados.setSize(600, 450);
        formempleados.setLocation(0,0);
        PanelActividades.removeAll();
        PanelActividades.add(formempleados, null);
        PanelActividades.revalidate();
        PanelActividades.repaint();
    }//GEN-LAST:event_EmpleadosActionPerformed

    private void PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacienteActionPerformed
       FormPacientes formpacientes = new FormPacientes();
        formpacientes.setSize(600, 450);
        formpacientes.setLocation(0,0);
        PanelActividades.removeAll();
        PanelActividades.add(formpacientes, null);
        PanelActividades.revalidate();
        PanelActividades.repaint();
    }//GEN-LAST:event_PacienteActionPerformed

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilActionPerformed

    private void AreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaActionPerformed
        FormArea formareas = new FormArea();
        formareas.setSize(600, 450);
        formareas.setLocation(0, 0);
        PanelActividades.removeAll();
        PanelActividades.add(formareas, null);
        PanelActividades.revalidate();
        PanelActividades.repaint();
        
    }//GEN-LAST:event_AreaActionPerformed

    private void CamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamasActionPerformed
        FormCamas formacamas = new FormCamas();
        formacamas.setSize(600, 450);
        formacamas.setLocation(0, 0);
        PanelActividades.removeAll();
        PanelActividades.add(formacamas, null);
        PanelActividades.revalidate();
        PanelActividades.repaint();
    }//GEN-LAST:event_CamasActionPerformed

    private void CampañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampañaActionPerformed
        FormCampana formcampana = new FormCampana();
        formcampana.setSize(600, 450);
        formcampana.setLocation(0, 0);
        PanelActividades.removeAll();
        PanelActividades.add(formcampana, null);
        PanelActividades.revalidate();
        PanelActividades.repaint();
    }//GEN-LAST:event_CampañaActionPerformed

    private void CitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitasActionPerformed
        FormCitas formcitas = new FormCitas();
        formcitas.setSize(600, 450);
        formcitas.setLocation(0, 0);
        PanelActividades.removeAll();
        PanelActividades.add(formcitas, null);
        PanelActividades.revalidate();
        PanelActividades.repaint();
    }//GEN-LAST:event_CitasActionPerformed

    private void InformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformesActionPerformed
        FormReportes formreportes = new FormReportes();
        formreportes.setSize(600, 450);
        formreportes.setLocation(0, 0);
        PanelActividades.removeAll();
        PanelActividades.add(formreportes,null);
        PanelActividades.revalidate();
        PanelActividades.repaint();
    }//GEN-LAST:event_InformesActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Area;
    private javax.swing.JButton Camas;
    private javax.swing.JButton Campaña;
    private javax.swing.JButton Citas;
    private javax.swing.JButton Empleados;
    private javax.swing.JButton Informes;
    private javax.swing.JLabel LabelImagen;
    private javax.swing.JButton Paciente;
    private javax.swing.JPanel PanelActividades;
    private javax.swing.JButton Perfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
