/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controlador.ControladorAgenda;
import Controlador.ControladorCausas;
import Controlador.ControladorCita;
import Controlador.ControladorRegistro;
import Logica.Paciente;
import Logica.Persona;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author Kevin
 */
public class InterfazConsultorio extends javax.swing.JPanel {
    private String idpaciente,idmedico;
    ControladorAgenda controlagenda = new ControladorAgenda();
    ControladorCausas controlcausas = new ControladorCausas();
    ControladorRegistro controlregistro = new ControladorRegistro();
    ControladorCita controlCita  = new ControladorCita();
    Persona persona = new Persona();
    /**
     * Creates new form InterfazConsultorio
     */
    public InterfazConsultorio(String id) {
        initComponents();
        this.idmedico=id;
        Grupo.add(Recetar_Medicamentos);
        Grupo.add(Asignar_Cama);
        DefaultComboBoxModel model;
        model = new DefaultComboBoxModel();
        controlcausas.Select_causas(model);
        this.Causas.setModel(model);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo = new javax.swing.ButtonGroup();
        Horario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Mes = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        Dia = new javax.swing.JSpinner();
        Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Recetar_Medicamentos = new javax.swing.JRadioButton();
        Asignar_Cama = new javax.swing.JRadioButton();
        Causas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        Terminar = new javax.swing.JButton();
        estadoccita = new javax.swing.JComboBox<>();

        Horario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00:00", "8:30:00", "9:00:00", "9:30:00", "10:00:00", "10:30:00", "11:00:00", "11:30:00", "12:00:00", "12:30:00", "13:00:00", "13:30:00", "14:00:00", "14:30:00", "15:00:00", "15:30:00", "16:00:00", "16:30:00", "17:00:00", "17:30:00", "18:00:00", "18:30:00", "19:00:00", "19:30:00", "20:00:00", "20:30:00", "21:00:00", "21:30:00" }));

        jLabel1.setText("Hora :");

        Mes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jLabel2.setText("Mes");

        jLabel3.setText("Dia");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Dia.setModel(new javax.swing.SpinnerNumberModel(1, null, 31, 1));

        Nombre.setEditable(false);

        jLabel4.setText("Nombre Paciente :");

        jLabel5.setText("Identificacion : ");

        Id.setEditable(false);

        Recetar_Medicamentos.setText("Recetar Medicamentos");
        Recetar_Medicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Recetar_MedicamentosMouseClicked(evt);
            }
        });
        Recetar_Medicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Recetar_MedicamentosActionPerformed(evt);
            }
        });

        Asignar_Cama.setText("Asignar Cama");
        Asignar_Cama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Asignar_CamaMouseClicked(evt);
            }
        });
        Asignar_Cama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asignar_CamaActionPerformed(evt);
            }
        });

        Causas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Causas de visita");

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Descripcion.setColumns(20);
        Descripcion.setRows(5);
        jScrollPane1.setViewportView(Descripcion);

        Terminar.setText("Terminar Consulta");
        Terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminarActionPerformed(evt);
            }
        });

        estadoccita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asistida", "No Asistida" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Buscar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Horario, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Id, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(Nombre)))
                            .addComponent(Asignar_Cama)
                            .addComponent(Recetar_Medicamentos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Causas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Terminar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(estadoccita, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(Buscar)
                    .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Causas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Asignar_Cama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Recetar_Medicamentos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Terminar)
                    .addComponent(estadoccita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String Hora,dia,mes;
        
        Hora=Horario.getSelectedItem().toString();
        dia=Dia.getValue().toString();
        mes=Mes.getValue().toString();
        controlagenda.Buscar(persona,idmedico, mes, dia, Hora);
        Nombre.setText(persona.getNombre());
        Id.setText(persona.getIdentificacion());
        idpaciente=persona.getIdentificacion();
        
    }//GEN-LAST:event_BuscarActionPerformed

    private void Recetar_MedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Recetar_MedicamentosMouseClicked
        FormFormula formAgenda = new FormFormula(idpaciente,idmedico);
        formAgenda.setSize(600, 450);
        formAgenda.setLocation(0,0);
        JFrame ventana = new JFrame();
        ventana.setSize(600, 450);
        ventana.setContentPane(formAgenda);
    }//GEN-LAST:event_Recetar_MedicamentosMouseClicked

    private void Asignar_CamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Asignar_CamaMouseClicked
        
    }//GEN-LAST:event_Asignar_CamaMouseClicked

    private void Asignar_CamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asignar_CamaActionPerformed
        Calendar calendario = new GregorianCalendar();
        int año = calendario.get(Calendar.YEAR);
        String fechacama = año+"-"+Mes.getValue().toString()+"-"+Dia.getValue().toString();
        Paciente_Cama formAgenda = new Paciente_Cama(idpaciente,fechacama);
        formAgenda.setSize(330, 180);
        formAgenda.setLocation(0,0);
        JFrame ventana = new JFrame();
        ventana.setSize(330, 250);
        ventana.setContentPane(formAgenda);
        ventana.setVisible(true);
    }//GEN-LAST:event_Asignar_CamaActionPerformed

    private void Recetar_MedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Recetar_MedicamentosActionPerformed
        FormFormula formAgenda = new FormFormula(idpaciente,idmedico);
        formAgenda.setSize(600, 450);
        formAgenda.setLocation(0,0);
        JFrame ventana = new JFrame();
        
        ventana.setSize(600, 450);
        ventana.setContentPane(formAgenda);
        ventana.setVisible(true);
    }//GEN-LAST:event_Recetar_MedicamentosActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        Calendar calendario = new GregorianCalendar();
        int año = calendario.get(Calendar.YEAR);
        String fechac=año+"-"+Mes.getValue().toString()+"-"+Dia.getValue().toString();
        if(!Descripcion.getText().equals("")){
           controlregistro.Insert_registro(idmedico, idpaciente, Causas.getSelectedItem().toString(), fechac, Descripcion.getText());
       }
    }//GEN-LAST:event_AgregarActionPerformed

    private void TerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminarActionPerformed
        Calendar calendario = new GregorianCalendar();
        int año = calendario.get(Calendar.YEAR);
        String fechac=año+"-"+Mes.getValue().toString()+"-"+Dia.getValue().toString();
        controlCita.Update_citatermina(idpaciente, idmedico, Horario.getSelectedItem().toString(), fechac, estadoccita.getSelectedItem().toString());
    }//GEN-LAST:event_TerminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JRadioButton Asignar_Cama;
    private javax.swing.JButton Buscar;
    private javax.swing.JComboBox<String> Causas;
    private javax.swing.JTextArea Descripcion;
    private javax.swing.JSpinner Dia;
    private javax.swing.ButtonGroup Grupo;
    private javax.swing.JComboBox<String> Horario;
    private javax.swing.JTextField Id;
    private javax.swing.JSpinner Mes;
    private javax.swing.JTextField Nombre;
    private javax.swing.JRadioButton Recetar_Medicamentos;
    private javax.swing.JButton Terminar;
    private javax.swing.JComboBox<String> estadoccita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
