/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controlador.ControladorFormula;
import Controlador.ControladorFormulaMedicamento;
import Controlador.ControladorMedicamento;
import Controlador.ControladorMedico;
import Controlador.ControladorPaciente;
import Controlador.ControladorPersona;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Leydi
 */
public class RegistroFormula extends javax.swing.JPanel {
        ControladorPersona controlpersona = new ControladorPersona();
        ControladorPaciente controlpaciente = new ControladorPaciente();
        ControladorMedico controlmedico = new ControladorMedico();
        ControladorFormula controlformula = new ControladorFormula();
        ControladorMedicamento controlmedicamento = new ControladorMedicamento();
        ControladorFormulaMedicamento control = new ControladorFormulaMedicamento();
        SimpleDateFormat formato = new SimpleDateFormat("d/MM/yyyy");
        Date fechacale;
        String idpaciente,idmedico;
        /**
     * Creates new form PerfilEnfermera
     */
    public RegistroFormula(String idpaciente,String idmedico) {
        this.idpaciente=idpaciente;
        this.idmedico=idmedico;
        initComponents();
        Medico.setText(idmedico);
        Paciente.setText(idpaciente);
        DefaultComboBoxModel Medica;
        Medica = new DefaultComboBoxModel();
        controlmedicamento.Select_medica(Medica);
        this.tengo.setModel(Medica);
        Nombre.setText(controlmedicamento.selec_nombre(tengo.getSelectedItem().toString()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IdFormula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Fecha = new com.toedter.calendar.JDateChooser();
        Paciente = new javax.swing.JTextField();
        Medico = new javax.swing.JTextField();
        tengo = new javax.swing.JComboBox<>();
        Medicamento = new javax.swing.JLabel();
        Cantidad = new javax.swing.JSpinner();
        Nombre = new javax.swing.JTextField();

        jLabel1.setText("Identificacion Formula :");

        jLabel3.setText("Indentificacion Medico :");

        jLabel5.setText("Identificacion Paciente :");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("Registrar Formula");

        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha:");

        Paciente.setEditable(false);

        Medico.setEditable(false);

        tengo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tengo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tengoItemStateChanged(evt);
            }
        });

        Medicamento.setText("Medicamento");

        Nombre.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Atras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Guardar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Medicamento)
                                .addGap(58, 58, 58)
                                .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdFormula)
                            .addComponent(Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(Paciente)
                            .addComponent(Medico)
                            .addComponent(tengo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdFormula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Medico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tengo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Medicamento)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Atras))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
     String formula,idPaciente,idMedico;
     try{
      if(IdFormula.getText().equals("")){
          JOptionPane.showMessageDialog(this,"Ingresa id formula");
      }else{
              if(controlformula.Comprobar_id(IdFormula.getText())){
                  JOptionPane.showMessageDialog(this,"Ingresa id ya existente");
              }else{
                    fechacale = Fecha.getDate();
                    formula=IdFormula.getText();
                    idPaciente=idpaciente;
                    idMedico=idmedico;
                    String  fecha=formato.format(fechacale);

                    controlformula.Insert_formula(formula, idMedico, idPaciente,fecha);
                    control.Insert_formulamedicamento(formula, tengo.getSelectedItem().toString(), Cantidad.getValue().toString());
                    
                    FormFormula formformula = new FormFormula(idpaciente,idmedico);
                    formformula.setSize(600, 450);
                    formformula.setLocation(0, 0);
                    this.removeAll();
                    this.add(formformula,null);
                    this.revalidate();
                    this.repaint();
              }
      }
     }catch(java.lang.NullPointerException e)
     {JOptionPane.showMessageDialog(this, "escoge una fecha!", "Error!", JOptionPane.ERROR_MESSAGE);}
    
     
      
    }//GEN-LAST:event_GuardarActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
       FormFormula formformula = new FormFormula(idpaciente,idmedico);
       formformula.setSize(600, 450);
       formformula.setLocation(0,0);
       this.removeAll();
       this.add(formformula, null);
       this.revalidate();
       this.repaint();
    }//GEN-LAST:event_AtrasActionPerformed

    private void tengoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tengoItemStateChanged
        String medicap = tengo.getSelectedItem().toString();
       Nombre.setText(controlmedicamento.selec_nombre(medicap));
    }//GEN-LAST:event_tengoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JSpinner Cantidad;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField IdFormula;
    private javax.swing.JLabel Medicamento;
    private javax.swing.JTextField Medico;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Paciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> tengo;
    // End of variables declaration//GEN-END:variables
}
